name: CrystalEggFactory
main: com.crystalcraftmc.crystaleggfactory.CrystalEggFactory
version: 0.2
authors: [Jwood9198, Jacc734, jflory7]
commands:
   egg:
      description:
         Used to place spawn eggs in your inventory which in the future will not be able to change spawners
      usage:
         /<command> <mob-type> <amountEggs>
   egglist:
      description:
         Will display all possible values of the mob-type attribute
      usage:
         /<command>
   eggban:
      description:
         Used to ban the use of eggs in a particular area
      usage:
         /<command><x1Coord><z1Coord><x2Coord><z2Coord><name_id>
   eggbanlist:
      description:
         Lists the names and locations of all egg-banned areas
      usage:
         /<command>
   eggunban:
      description:
         Unbans egg-use in the specified id_name area
      usage:
         /<command><name_id>
   eggbanworld:
      description:
         Allow/disallow eggs in a certain world (banned areas still apply)
      usage:
         /<command><end/overworld/nether><true/false>
         
permissions:
   CrystalEggFactory.use:
      description:
         Allows use of all CrystalEggFactory commands, as well as the ability to bypass
         banned egg areas
      default: op
         
